# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sqlite3
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def book(self):
        book=sqlite3.connect("book.db")
        curbook=book.cursor()
        nm=self.t1.text()
        curbook.execute("Select Price from book WHERE Title='"+nm+"';")
        record=curbook.fetchall()
        if record==None:
            self.tc1.setText("Book  not found!!")
        else:
            for i in record :
                for j in i :
                    self.tc1.setText(str(j))

    def price(self):
        qty=(self.t2.text())
        self.tc2.setText(str(qty*self.tc1.text()))
        
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(493, 300)
        self.t1 = QtWidgets.QLineEdit(Form)
        self.t1.setGeometry(QtCore.QRect(200, 50, 113, 22))
        self.t1.setObjectName("t1")
        self.t2 = QtWidgets.QLineEdit(Form)
        self.t2.setGeometry(QtCore.QRect(200, 170, 113, 22))
        self.t2.setObjectName("t2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(90, 50, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(90, 170, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(70, 130, 261, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(90, 110, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(100, 220, 55, 16))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.b1 = QtWidgets.QPushButton(Form)
        self.b1.setGeometry(QtCore.QRect(360, 50, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b1.setFont(font)
        self.b1.setObjectName("b1")
        self.b2 = QtWidgets.QPushButton(Form)
        self.b2.setGeometry(QtCore.QRect(360, 170, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Comic Sans MS")
        font.setPointSize(10)
        self.b2.setFont(font)
        self.b2.setObjectName("b2")
        self.tc1 = QtWidgets.QLineEdit(Form)
        self.tc1.setGeometry(QtCore.QRect(200, 110, 113, 22))
        self.tc1.setObjectName("tc1")
        self.tc2 = QtWidgets.QLineEdit(Form)
        self.tc2.setGeometry(QtCore.QRect(200, 220, 113, 22))
        self.tc2.setObjectName("tc2")
        self.b1.clicked.connect(self.book)
        self.b2.clicked.connect(self.price)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Book Title :"))
        self.label_2.setText(_translate("Form", "Quantity :"))
        self.label_3.setText(_translate("Form", "Price :"))
        self.label_6.setText(_translate("Form", "Total :"))
        self.b1.setText(_translate("Form", "Find Price"))
        self.b2.setText(_translate("Form", "Find Total"))
        self.tc1.setText(_translate("Form", "Rs. 0"))
        self.tc2.setText(_translate("Form", "Rs. 0"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

